name: Simple CI Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print current directory
        run: pwd
        
      - name: print python version
        run: python3 --version

      - name: list files in the repository
        run: ls -la